spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Project?createDatabaseIfNotExist=true&useSSL=false&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Kiev&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: STRONGpwd1$

  jpa:
    hibernate:
      show_sql: true
      format_sql: true
      ddl-auto: update
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

date-time:
  timezone: Europe/Kiev

logging:
  level:
    root: warn
    com.unfu.project: debug

jwt:
  secret: tXmwC4o6aOoHUaKhZjuhxTb20p2abQaX
  expirationInMs: 360000000000000

google:
  clientId: 217658242103-pv74qrnmoku2aqhtgre77kutpfuk1sqe.apps.googleusercontent.com
  clientSecret: aNTs-K0fYvd72CyyjzTc21_u
